[build]
  base = "web/"
  publish = "web/.next"
  environment = { NODE_VERSION = "14", AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[context.production]
  command = "yarn run build"

[functions]
  directory = "web/functions/"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"