[build]
  publish = ".next"
  environment = { NODE_VERSION = "14", AWS_LAMBDA_JS_RUNTIME = "nodejs14.x" }

[context.production]
  command = "yarn run build"

[functions]
  directory = "functions/"
  external_node_modules = ["sharp"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@netlify/plugin-functions-install-core"