module.exports = {
  COMPANY_NAME: "Bert's Painting & Decorating",
  COMPANY_OWNER: 'Bert Laroche',
  COMPANY_EMAIL: 'bert@bertspainting.ca',
  COMPANY_DOMAIN: 'bertspainting.ca',
  COMPANY_PHONE_MAIN: '204-233-5201',
  COMPANY_PHONE_CELL: '204-782-4314',
  COMPANY_ADDRESS_STREET: '135 Birchdale Ave.',
  COMPANY_ADDRESS_CITY: 'Winnipeg',
  COMPANY_ADDRESS_PROVINCE: 'Manitoba',
  COMPANY_ADDRESS_POSTAL: 'R2H 1S3',
  COMPANY_DESCRIPTION:
    "Bert's Painting & Decorating is a father and son company providing service in English and French to many satisfied customers for over 35 years. We are Red Seal Qualified Journeyman Painters providing interior and exterior work in residential and small commercial buildings.",
  COMPANY_REVIEW_LINK: 'https://g.page/r/CXvnd3cgbT9lEAg/review',
  COMPANY_ADDRESS_LINK:
    "https://google.com/maps/search/Bert's+Painting+%26+Decorating/@49.87607,-97.132592,17z",
  FORM_MAILER_PATH: '.netlify/functions/form-mailer',
  RECAPTCHA_VERIFY_PATH: '.netlify/functions/recaptcha-verify',
  siteRoutes: [
    '/',
    '/about',
    '/services',
    '/portfolio',
    '/testimonials',
    '/contact',
  ],
  mediaQueries: {
    mobileS: '320px',
    mobileM: '375px',
    mobileL: '425px',
    tablet: '768px',
    laptop: '1024px',
    laptopL: '1440px',
    desktop: '2560px',
  },
};
