const ACCEPTED_HTTP_METHODS = ['POST'];
const FORM_EMAIL_INPUT_KEY = 'email';
const FORM_NAME_INPUT_KEY = 'name';
const FORM_DETAILS_INPUT_KEY = 'details';
const FORM_TYPE_INPUT_KEY = 'type';

module.exports = {
  ACCEPTED_HTTP_METHODS,
  FORM_EMAIL_INPUT_KEY,
  FORM_NAME_INPUT_KEY,
  FORM_DETAILS_INPUT_KEY,
  FORM_TYPE_INPUT_KEY,
};
